# Generated by Django 4.2.13 on 2024-06-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productcustomization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcustomization',
            name='product_image',
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
