# Generated by Django 4.2.13 on 2024-06-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productcustomization_about_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
