# Generated by Django 4.2.13 on 2024-06-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='benefits',
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.ManyToManyField(to='store.benefit'),
        ),
    ]
