# Generated by Django 4.2.13 on 2024-07-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_information_product_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.CharField(blank=True, default='', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
    ]
