# Generated by Django 4.2.13 on 2024-07-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_copy_info_alter_product_domain_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hosting_info',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
