# Generated by Django 4.2.13 on 2024-07-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_hosting_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarantee_info',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
