# Generated by Django 4.2.13 on 2024-07-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_guarantee_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='guarantee_info',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
