# Generated by Django 4.2.13 on 2024-07-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_guarantee_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo_info',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_info',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
